version: 2
general:
  branches:
    only:
      - master
jobs:
  publish:
    docker:
      - image: circleci/node:10.12-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - run: yarn publish --non-interactive

workflows:
  version: 2
  publish:
    jobs:
      - publish
        filters:
          branches:
              only: master
